[toolchain]
anchor_version = "1.0.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_kredence = "EMrHDb9yk3cjnnj2czRa7MRi6PTjWJukUnZ2Zt3jWNv6"

[programs.localnet]
anchor_kredence = "J8zY5tEUxTsz5U6EUPyreRn4vU2ZrxutWAWZtxyJptbp"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=607fb582-f22d-48ff-be88-cde253c0f014"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"

[[test.validator.clone]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"

[[test.validator.clone]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
