[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_kredence = "J8zY5tEUxTsz5U6EUPyreRn4vU2ZrxutWAWZtxyJptbp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
